### ISSUE TITLE
HTML autosave logs

### ISSUE THREAD

**Issue by Dmitriy147** [PFalkowski/LoggerLite#4]
Is it possible to make? - as I understand, to write message to file I need to call Save method after every message.
..I am working in .Net 5 and need logger with html log, threadsafe, making log files every day with Date.html names...

**Comment by PFalkowski** [comment]
Hello Dmitriy, yes, as you probably spotted, you just need to call `logger.Save(outputFile); ` after each` Log()` action or in some time intervals. I would suggest deriving from `HtmlLogger` and overriding Log method. Here is an example snippet:


```
    public class AutoSaveHtmlLogger : HtmlLogger
    {
        private readonly FileInfo _file;

        public AutoSaveHtmlLogger(FileInfo file)
        {
            _file = file;
        }

        protected override void Log(string message, MessageSeverity severity)
        {
            base.Log(message, severity);
            base.Save(_file);
        }
    }
```
